export default MesDatas = [
  {
    id:1,
    shop:'1',
    status:'pending',
    percent:'10',
    Beneficiary:'1',
    validity:'2020-10-11'
  },
  {
    id:2,
    shop:'2',
    status:'pending',
    percent:'11',
    Beneficiary:'1',
    validity:'2020-10-11'
  },
  {
    id:3,
    shop:'2',
    status:'pending',
    percent:'12',
    Beneficiary:'1',
    validity:'2020-10-11'
  },
]
